name: Build KivyMD APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_HOME: ${{ runner.home }}/android-sdk
      PATH: ${{ runner.home }}/android-sdk/platform-tools:${{ runner.home }}/android-sdk/cmdline-tools/latest/bin:$PATH

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            python3-pip git zip unzip openjdk-17-jdk \
            autoconf libtool pkg-config zlib1g-dev libc6-dev \
            libncurses5-dev libstdc++6 python3-dev python3-setuptools \
            python3-wheel build-essential ccache libffi-dev \
            libssl-dev libsqlite3-dev wget curl

      - name: Install Android SDK & Build-tools
        run: |
          mkdir -p $ANDROID_HOME/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d $ANDROID_HOME/cmdline-tools
          rm cmdline-tools.zip
          mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest
          yes | sdkmanager --sdk_root=$ANDROID_HOME "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Install Buildozer & Cython
        run: |
          pip install --upgrade pip
          pip install buildozer cython

      - name: Initialize buildozer
        run: |
          if [ ! -f buildozer.spec ]; then
            buildozer init
          fi

      - name: Build debug APK
        run: buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: Calculator-APK
          path: bin/*.apk
