name: Build APK

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y git zip unzip openjdk-17-jdk wget python3-pip build-essential
        python3 -m pip install --upgrade pip
        pip install cython buildozer kivy kivymd

    - name: Setup JAVA_HOME
      run: |
        echo "JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64" >> $GITHUB_ENV
        echo "/usr/lib/jvm/java-17-openjdk-amd64/bin" >> $GITHUB_PATH

    - name: Download Android SDK and NDK
      run: |
        mkdir -p $HOME/android
        cd $HOME/android
        # دانلود SDK command-line tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip
        mv cmdline-tools latest
        rm cmdline-tools.zip
        # دانلود NDK r25b
        wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
        unzip android-ndk-r25b-linux.zip
        rm android-ndk-r25b-linux.zip

    - name: Configure Buildozer
      run: |
        buildozer android clean
        buildozer android debug \
          --sdk-path=$HOME/android \
          --ndk-path=$HOME/android/android-ndk-r25b

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: Calculator-APK
        path: bin/*.apk
